// Generated by Bisonc++ V6.01.03 on Tue, 26 Mar 2019 15:18:07 +0100

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "Parserbase.h"
#include "../scanner/scanner.h"


#undef Parser
    // CAVEAT: between the baseclass-include directive and the 
    // #undef directive in the previous line references to Parser 
    // are read as ParserBase.
    // If you need to include additional headers in this file 
    // you should do so after these comment-lines.


class Parser: public ParserBase
{

    Scanner d_scanner;

    public:
        Parser() = default;
        int parse();
        
        void showInt(STYPE__ const &val) const;
        void showString(STYPE__ const &val) const;
        void showDouble(STYPE__ const &val) const;
        void quit();

    private:
        void error();                   // called on (syntax) errors
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction__(int ruleNr);
        void errorRecovery__();
        void nextCycle__();
        void nextToken__();
        void print__();
};


#endif
